spring:
  application:
    name: secure-server
    
server:
  port: 8443
  ssl:
    key-store: /Users/cchrysostom/github.com/codependent/spring-boot-ssl-mutual-authentication/server-keystore.jks
    key-store-password: secret
    key-alias: secure-server
    trust-store: /Users/cchrysostom/github.com/codependent/spring-boot-ssl-mutual-authentication/server-truststore.jks
    trust-store-password: secret
    enabled: true
    client-auth: need
    
logging:
  level:
    org.springframework.security: DEBUG